site_name: Vocabulary - Maverick Annotation Framework

theme: 
  palette: 
    scheme: default
    primary: red 
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
