site_name: Entity Annotation Framework
extra_css: 
   - assets/stylesheets/extra.css

theme: 
  name: material
  custom_dir: overrides

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    

  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.tabs  
    - content.tabs.link
    
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bechtleav360

nav: 
    - "Definitions": 
      - "Layers": "definitions/Layers.md"
      - "Annotations": "definitions/Annotations.md"
      - "Recommendations": "definitions/Recommendations.md"
      - "Journey": "definitions/Journey.md"
      - "Feedback": "definitions/Feedback.md"
    - "Classes": 
      - "Recommendation": "classes/Recommendation.md"
    - "Properties":
      - "Explanation": "properties/explanation.md"
      - "Recommendations": 
        - "source": "properties/recommendations/source.md"
        - "story": "properties/recommendations/story.md"
        - "audience": "properties/recommendations/audience.md"
        - "confidence": "properties/recommendations/confidence.md"
      - "Metrics": 
        - "acknowledged": "properties/feedback_metrics/acknowledgeCount.md"
        - "ignored": "properties/feedback_metrics/ignoreCount.md"
        - "confirmed": "properties/feedback_metrics/confirmCount.md"
        - "rejected": "properties/feedback_metrics/rejectCount.md"
      - "Annotations":
        - "confidence": "properties/annotations/confidence.md"
        - "explanation": "properties/annotations/explanation.md"
        - "model": "properties/annotations/model.md"
        - "created": "properties/annotations/created.md"
        - "status": "properties/annotations/status.md"
        - "updated": "properties/annotations/updated.md"
        - "cosSimilarity": "properties/annotations/cosSimilarity.md"
      #- "Explicit Feedback":
        #- "empty": "properties/explicit_feedback/empty.md"

  

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower